// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVAVSL615awNjP_qOyiZ0cWMFOR7h6tYo',
    appId: '1:489323196307:web:9dc3f7705660fe4e010266',
    messagingSenderId: '489323196307',
    projectId: 'student-75ae2',
    authDomain: 'student-75ae2.firebaseapp.com',
    storageBucket: 'student-75ae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdAuA3YdoJjxYwni2sSnlgcztl9-hnPY',
    appId: '1:489323196307:android:1e30cca2fa8f0669010266',
    messagingSenderId: '489323196307',
    projectId: 'student-75ae2',
    storageBucket: 'student-75ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfm6TdK9iEB2AmPgX7HC6DvjqozpqnnM8',
    appId: '1:489323196307:ios:172b45332e50c27c010266',
    messagingSenderId: '489323196307',
    projectId: 'student-75ae2',
    storageBucket: 'student-75ae2.appspot.com',
    iosBundleId: 'com.example.studentdetails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfm6TdK9iEB2AmPgX7HC6DvjqozpqnnM8',
    appId: '1:489323196307:ios:12935f38f2d07be8010266',
    messagingSenderId: '489323196307',
    projectId: 'student-75ae2',
    storageBucket: 'student-75ae2.appspot.com',
    iosBundleId: 'com.example.studentdetails.RunnerTests',
  );
}
